name: Mirror

on:
  push:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Push to GitShark
        env:
          GITSHARK_TOKEN: ${{ secrets.GITSHARK_TOKEN }}
        run: |
          git remote set-head origin -d
          git push --force --prune \
            "https://token:${GITSHARK_TOKEN}@gitshark.ha1nz.de/git/miggi/GitShark.git" \
            'refs/remotes/origin/*:refs/heads/*' \
            'refs/tags/*:refs/tags/*'
