name: Native

on:
  push:
    branches: [main]
  pull_request:

jobs:
  native-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Native build
        run: ./mvnw -B package -Dnative -DskipTests -Dquarkus.native.container-build=true
